# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53383532f12028c6f758b599452e8fe21504a745506309d17ac2b6418c19758b69131863c9a8442eb8d16c52ca8778100ea7e313a681e43281e90bd943dd559f

test:
  secret_key_base: 10019bb375bb6945d783680c5f633d4b7514bbcea64be7121728ee1d012b330e830f0d6de7acb5ddeff345fc3409a9d162879c8ccd51ba01ce3321df4e544cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
